cam_model: Pinhole
cam_width: 1280
cam_height: 720
scale: 0.5
cam_fx: 769.1234741210938
cam_fy: 768.9295654296875
cam_cx: 642.66455078125
cam_cy: 352.95428466796875
cam_d0: 0.0
cam_d1: 0.0
cam_d2: 0.0
cam_d3: 0.0